### ISSUE TITLE
July 2019 Meetup (Closed for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#10]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/260564102/?isFirstPublish=true)
- [x] Date: Thursday, 25th July 2019 
- [x] Venue: Stripe Singapore 
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

**Comment by rodrigobdz** [comment]
## ReactJS for slow internet connections

**Talk description**

There have been many articles recently about the importance of web performance [[1]](https://developers.google.com/web/fundamentals/performance/why-performance-matters/)[[2]](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/) but still most of the applications focus more on offering a ton of features rather than on making these accessible to a larger audience.

While volunteering in West Africa last month I became aware of the need to design applications for slow internet connections to be inclusive. As internet use is growing in Africa [[3]](https://www.pewglobal.org/2018/10/09/internet-use-is-growing-across-much-of-sub-saharan-africa-but-most-are-still-offline/), this opens a whole new market because people in remote areas often choose products primarily according to their data usage and not according to what they offer.

In this talk I will present common pitfalls and how to optimize your application to increase your customer acquisition rate.

**Presenter**

Rodrigo Bermudez Schettino
GitHub: @rodrigobdz
Web: https://rodrigobdz.github.io
LinkedIn: https://linkedin.com/in/rodrigobdz

**Presenter's bio**

Currently working full-time in Singapore. CS graduate student with major in AI at [TU Berlin](https://tu-berlin.de).

I have over five years of professional experience in IT Consulting and Software Development where I learned to optimize (web) applications for performance. 

**Duration requested**

20 min

**Slides URL (if any)**

Coming soon…

**Comment by yosriady** [comment]
@rodrigobdz Thank you for sending in your talk! I'm looking forward to have you speak at the July meetup :+1:

**Comment by tanhauhau** [comment]
# React Hooks Visualized

## Talk description

Inspired by [Philip Roberts's JSConf EU's talk](https://www.youtube.com/watch?v=8aGhZQkoFbQ), I build a [react hook visualiser](https://lihautan.com/react-hooks-visualiser/)!
Following the [Hooks! talk](https://github.com/ReactJSSG/meetups/issues/9#issuecomment-476072696), I will be speaking in depth of what actually happens under the hood when you call hooks. 

## Presenter
Tan Li Hau
http://lihautan.com
https://github.com/tanhauhau
https://twitter.com/lihautan

## Presenter's bio
My name is Li Hau, I am a web frontend engineer in Shopee. I like to build stuff and share what I know to the world.

## Duration requested
30min

## Slides URL
Will add later

**Comment by yosriady** [comment]
@tanhauhau See you in July! 👏

**Comment by ais-one** [comment]
Moved to August...

https://github.com/ReactJSSG/meetups/issues/12#issuecomment-502529958

**Comment by yishus** [comment]
## Suspense, `react-cache` and thoughts on data fetching

**Talk description**

Redux has become the de facto library for data fetching but most of us haven't gotten down to think about the why. This talk dives into design patterns and thoughts on designing the data layer for React apps and how the upcoming suspense model will change how you approach data fetching.

**Presenter**

Yishu See
GitHub: @yishus
Twitter: @yishusee

**Presenter's bio**

Yishu is bad at things. Bouldering, speaking Japanese, crow pose; all bad. Thank goodness she's okay at making computers do things. Currently she is a software engineer at Carousell, contributing to the web platform. Before that in her career, she has taken on multiple roles - iOS engineer, backend engineer and fleetingly a product designer. Her current favourite function is .split().

**Duration requested**

25 min

**Slides URL (if any)**

WIP

**Comment by yosriady** [comment]
@ais-one @yishus We're all full at 3 speakers for the July meetup, do you mind going for the August meetup instead? You can submit here: https://github.com/ReactJSSG/meetups/issues/12

**Comment by nickthepayne** [comment]
@yosriady is the venue set in stone? We would be happy to host a meetup and since I will be speaking in July I could to talk to management about it (Spaces, Robinson Rd)

**Comment by yosriady** [comment]
@enpayne Yes, it's set. We have Stripe as our venue sponsor for the July meetup. Alternatively, you can also present in August.

**Comment by nickthepayne** [comment]
@yosriady I sent you an email regarding the August meetup location last week, did you see that? Or how can I get in touch with you?

**Comment by yosriady** [comment]
@enpayne Sorry, I missed your email. I've sent you a reply.

**Comment by jfrolich** [comment]
@yosriady: Still open for a lightning talk in July?

**Comment by yosriady** [comment]
@jfrolich Yes, I think we can squeeze in one more (5 mins.)

**Comment by tanhauhau** [comment]
@yosriady Sorry, I am a bit overwhelming recently, i don't think i can give a talk for the July meetup, i wish to give up my slot.

**Comment by yosriady** [comment]
@tanhauhau Got it, thanks for the update.

**Comment by jfrolich** [comment]
## Best practices for building a high quality React-Native app

**Talk description**
During this lightning talk I will share some of the learnings and gotchas on how to create a high quality mobile experience that is indistinguishable from a "real" native app on iOS and Android. This is mostly from my experience in building the recently launched Family Five (https://familyfive.app), a parenting app, that has been featured in the Apple App Store.

**Presenter(s)**
Jaap Frölich. @jfrolich, https://twitter.com/JaapFrolich.

**Presenter's bio**
Jaap is the co-founder of Family Five. He has a background in (Industrial) Design and Data Science (Econometrics), but for the past years has been working on multiple mobile and web products. He has been using React since it launched in 2013.

**Duration requested**
5min (Lightning Talk)

**Slides URL (if any)**
[ReactMeetup V2.pdf](https://github.com/ReactJSSG/meetups/files/3434022/ReactMeetup.V2.pdf)

**Comment by jfrolich** [comment]
I didn't hear anything. Is my lightning talk still happening, or do I need to submit it for another meetup?

**Comment by yosriady** [comment]
@jfrolich Yes, you're in. Sorry, I thought https://github.com/ReactJSSG/meetups/issues/10#issuecomment-509508105 already confirmed it.

**Comment by yosriady** [comment]
@rodrigobdz @yishus @enpayne @jfrolich Looking forward to your talks later! Please reply to this comment to confirm your attendance.

**Comment by rodrigobdz** [comment]
See you later!

**Comment by jfrolich** [comment]
Added my slides
