### ISSUE TITLE
May 2019 Meetup (Closed for Speakers)

### ISSUE THREAD

**Issue by yosriady** [ReactJSSG/meetups#9]
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/259917189/)
- [x] Date: Wednesday, 22nd May 2019
- [x] Venue: Zendesk Singapore
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 5min (Lightning Talk), 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [x]  Confirm date and venue availability 
- [x]  Create event on [React JS SG Meetup Page](https://www.meetup.com/React-Singapore)

</details>

**Comment by lisaMartini** [comment]
Title of your talk

**Interfacing an OLAP cube with a react chatbot**

Talk description
**Describing the chatbot implementation and how it interacts with the ActivePivot OLAP cube**.

Tell us what you'd like to talk about:

* Brief introduction of OLAP cube and MDX query language
* How to implement a chatbot based on react-simple-chatbot component
* How to use Wit.ai as a Natural Language Processing
* Prototype demo

Presenter(s)

Presenter's bio
Nida Bouzid , Java developer in Singapore since 8 years. Github : [nidaBouzid](https://github.com/nidaBouzid)
Lisa Martini, Full stack developer in Singapore since 2018. Github : [lisaMartini](https://github.com/lisaMartini) and [ewilys](https://github.com/ewilys)

Duration requested
30 min
Preferably beginning of May

**Comment by yosriady** [comment]
@lisaMartini 

Thank you for sending a proposal! I think chatbots would be of interest to the community, but I think OLAP wouldn't be of interest to most developers in the community. I would recommend keeping the talk strictly around React by focusing more on the chatbot aspects, and cutting on the OLAP / MDX / ActivePivot.

What do you think?

**Comment by nidabouzid** [comment]
Hi @yosriady 
The chatbot has been implemented to simplify the interaction with an OLAP database, if we do not introduce the OLAP part we remove the context of what we want to show ... If you still don't want us to mention  LAP / MDX / ActivePivot consider us out.

**Comment by yosriady** [comment]
Hi @nidabouzid 

In that case, I'll decline this proposal. Thanks for sending it in!

**Comment by lzhuor** [comment]
## Functional JavaScript with Ramda.js
**Description**
How Ramda.js enables our front-end team to write practical, elegant, readable and maintainable functional JavaScript? 
- Everyone in the team becomes happier because writing FP is fun!
- We don't have `lodash` in our dependencies. 

This presentation will cover:
- Basic FP theories to understand Ramda.js
- Why it could be a good replacement for `lodash`? 
- Walk through some code snippets: Certain FP patterns elegantly resolve real-life React / Redux problems
  - Catamorphism
  - Immutable data
  - and more

**Presenter(s)**
[John Li](https://github.com/lzhuor)

**Presenter Bio's**
Software Engineer at [Endowus](https://endowus.com).

John is a front-end engineer at [Endowus](https://endowus.com) -  a Singapore-based financial technology company that empowers people to take control of their financial future. The firm’s proprietary systems provide data-driven wealth advice in constructing personalised solutions. Its portfolios are built on access to institutional-quality financial products at the lowest cost possible.

**Duration requested**
30min

**Slide URL**
Coming soon

**Comment by yosriady** [comment]
@lzhuor Thank you for sending in your proposal. I'm looking forward to see you share at the May meetup!

**Comment by haldarmahesh** [comment]
# A deep dive in React's New Component Lifecycle Methods
#### Description

A short introduction about the importance of lifecycle methods and how React dev can write better React app if we know the right lifecycle method and its right use case.

This talk covers all the component lifecycle method after major updates in 16.4.
Then deep dive into all the React component lifecycle methods with use cases and code snippet basically to know how the method looks and what are its responsibilities.

We will take React music player app as reference to understand where and how the methods can be used.

#### Presenter(s)
[Mahesh Haldar](http://www.maheshhaldar.com/)

#### Presenter Bio's
Mahesh is Full stack Software Engineer, blogger and hindi story teller.
I solve problems, write blogs about topics like REST API, React, PWAs, etc and narrate hindi audio stories on Ek Lifafa (YouTube channel)

#### Duration requested
30min

#### Slide URL
Coming soon

**Comment by yosriady** [comment]
@haldarmahesh Looking forward to have you share at the May meetup! I'll update this thread once the date and venue is finalized.

**Comment by yosriady** [comment]
@lzhuor @haldarmahesh 

We've confirmed the date and venue of the May meetup to be **Wednesday, 22nd May 2019**
at **Zendesk Singapore**.

**Comment by huangkaiw3n** [comment]
React Native x Parking.sg
====================
#### Description
* Brief intro on RN
* Pros and cons encountered using RN in building [Parking.sg](https://parking.sg)
* The power of hot code push in RN
* Writing your own native modules in RN
* Q&A

#### Presenter(s)
[Huang Kaiwen](https://github.com/huangkaiw3n)

#### Presenter Bio's
Software Engineer at [Open Government Products (OGP)](https://open.gov.sg)

Kaiwen is one of the two main software engineers at OGP who built Parking.sg from scratch.

#### Duration requested
30min

#### Slide URL
[React Native x Parking.sg](https://docs.google.com/presentation/d/1gecBRPgQj-cNYR_hHqSHXqWNFYJqU6sJ8U5elPNK4HA/edit?usp=sharing)

**Comment by r0lodex** [comment]
# React-Boilerplate: Helping you and your team code better!

**Description**
React Boilerplate is a highly scalable, offline-first foundation with the best developer experience and a focus on performance and best practices. I think everyone should contribute to the code, it's open-source and super robust.

- Brief introduction on [React-Boilerplate](https://github.com/react-boilerplate/react-boilerplate)
- Why this boilerplate is awesome
- Power Demo
- Our experience
- Q&A

**Presenter**
[Tien Ping](https://github.com/tienping)

**Presenter Bio**
Senior Frontend Developer at [Hermo Malaysia](https://hermo.my), a beauty-tech ecommerce platform, #1 in Malaysia

**Duration Requested**
30 min

**Slide URL**
Coming soon

**Comment by li-kai** [comment]
## Hooks!
**Talk description**

React hooks are a brand new pattern, but how are they different from class components? In this talk, we'll take a deep dive into react hooks, its internals, and ways to easily test and build custom hooks.

**Presenter(s)**
@li-kai

**Presenter's bio**

Kai is a software engineer at [Zendesk](https://zendesk.com) - a customer service software and support ticketing system. 

He likes to build open source software and actively maintains [NUSMods](https://nusmods.com).

**Duration requested**
20min

**Slides URL (if any)**
[Google slides](https://docs.google.com/presentation/d/1vP66JggdsOR3IJCUiGEWuBqwLRtknMy-L0vU6Jr98rQ/edit?usp=sharing)

**Comment by yosriady** [comment]
@r0lodex Hi, we're all full for speakers in the May meetup, would you be interested in speaking at the [July meetup](https://github.com/ReactJSSG/meetups/issues/10) instead?

**Comment by yosriady** [comment]
@huangkaiw3n @li-kai Looking forward to see you at the May meetup!

**Comment by yosriady** [comment]
@li-kai @lzhuor @haldarmahesh @huangkaiw3n Looking forward to hear you share [tomorrow](https://www.meetup.com/React-Singapore/events/259917189/)! 👏 

> 📢 **Please reply with a comment to confirm that you will be speaking at the May meetup.**

**Comment by huangkaiw3n** [comment]
Yeah I'll be there. See you!

**Comment by haldarmahesh** [comment]
Hey, yes I will be there.
See ya :)

**Comment by lzhuor** [comment]
See you there! Thank you! @yosriady

**Comment by yosriady** [comment]
@li-kai @lzhuor @haldarmahesh @huangkaiw3n 

Hi folks, if you don't mind could you share your slides on the meetup page: https://www.meetup.com/React-Singapore/events/259917189/

Thanks.

**Comment by huangkaiw3n** [comment]
@yosriady Not sure how to add my slides there. But here's the link [https://go.gov.sg/rnxparking](https://go.gov.sg/rnxparking)

**Comment by yosriady** [comment]
You can leave a comment on the meetup comments section here: https://www.meetup.com/React-Singapore/events/259917189/ with the slide URL
